name: FOSSA Analysis

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'architeacher'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: FOSSA analysis
        uses: fossas/fossa-action@v1
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}
