name: Lint

on:
  push:
    branches: [ '*' ]
    paths:
      - '.github/**'
      - '**.go'
      - 'go.mod'
      - '**.yaml'
    tags: [ 'v*' ]
  pull_request:
    branches: [ '*' ]
    paths-ignore:
      - "**.md"
      - "assets/**"
      - "go.mod"

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read

jobs:
  golangci:
    name: Lint on ${{ matrix.os }} @ Go ${{ matrix.go }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        go: [ ^1 ]
        os: [ ubuntu-latest ]
        include:
          - go: ^1
            latest: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Setup Go ${{ matrix.go }}
        timeout-minutes: 5
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: golangci-lint
        if: success() && matrix.latest
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
